### ISSUE TITLE
Version 5.1.0 seem to miss MockitoSugar

### ISSUE THREAD

**Issue by renevangsgaardjp** [playframework/scalatestplus-play#281]
After upgrading to 5.1.0 I cannot find `MockitoSugar`.

The issue can be reproduced by cloning this project `https://github.com/Jyllands-Posten/play-prometheus-filters`. On branch `feature/upgrade-scalatestplay` the issue is present.

```
[error] /PATH/play-prometheus-filters/src/test/scala/com/github/stijndehaes/playprometheusfilters/controllers/PrometheusControllerSpec.scala:9:26: object mockito is not a member of package org.scalatestplus
[error] import org.scalatestplus.mockito.MockitoSugar
```

**Comment by raboof** [comment]
Perhaps depend on https://github.com/scalatest/scalatestplus-mockito directly?

**Comment by renevangsgaardjp** [comment]
Yes, it helped adding this dependency. Thank you.
`libraryDependencies += "org.scalatestplus" %% "mockito-3-4" % "3.2.1.0" % "test"`

Now we have an error regarding Scala symbols, but I am not sure if it is related to this project.

```
[info] PrometheusModule
[info] - should register default exporters when enabled *** FAILED ***
[info]   java.lang.IllegalArgumentException: Can't find a private method named: ymbol(collectors)
[info]   at org.scalatest.PrivateMethodTester$Invoker.invokePrivate(PrivateMethodTester.scala:247)
[info]   at com.github.stijndehaes.playprometheusfilters.PrometheusModuleSpec.$anonfun$new$3(PrometheusModuleSpec.scala:25)
```

**Comment by raboof** [comment]
> Yes, it helped adding this dependency. Thank you.

:+1: 

> I am not sure if it is related to this project

Hmm, indeed at first glance that looks like a general scalatest issue, not a scalatestplus-play issue (or perhaps something due to mismatched versions?)
